os: linux
dist: focal
language: ruby
rvm:
  - 3.0.0

# Install Node.js
node_js:
  - 16

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - node_modules

before_install:
  # Install Node.js
  - nvm install 16
  - nvm use 16
  # Install npm dependencies if you have a package.json
  - npm install
  # Install Ruby dependencies
  - gem install bundler
  - bundle config set path 'vendor/bundle'
  - rm -f Gemfile.lock

install:
  - bundle install

script:
  - bundle exec jekyll build

deploy:
  provider: pages
  strategy: git
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  keep_history: true
  edge: true
  on:
    branch: master
