os: linux
dist: focal
language: ruby
rvm:
  - 3.0.0

branches:
  only:
    - master  # Updated from main to master

cache:
  bundler: true

before_install:
  - gem install bundler
  - bundle config set path 'vendor/bundle'
  - rm -f Gemfile.lock

install:
  - bundle install

script:
  - bundle exec jekyll build

deploy:
  provider: pages
  strategy: git
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  keep_history: true
  edge: true
  on:
    branch: master  # Updated from main to master
