name: Deploy site

on:
  push:
    branches:
      - master
    paths:
      - "assets/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "Gemfile"
      - "Gemfile.lock"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Download and Install Ruby
        shell: pwsh
        run: |
          $rubyInstallerUrl = "https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.2-1/rubyinstaller-devkit-3.2.2-1-x64.exe"
          $installerPath = "$env:TEMP\rubyinstaller.exe"
          Invoke-WebRequest -Uri $rubyInstallerUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -Args "/verysilent /dir=C:\Ruby32-x64" -Wait
          $env:PATH = "C:\Ruby32-x64\bin;$env:PATH"
          [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "Machine")
          ruby --version
          gem install bundler

      - name: Install problematic gems
        shell: pwsh
        run: |
          $env:PATH = "C:\Ruby32-x64\bin;$env:PATH"
          gem install libv8-node -v '16.10.0.0' --platform=ruby
          gem install mini_racer -v '0.6.3'

      - name: Update Gemfile
        shell: pwsh
        run: |
          (Get-Content Gemfile) -replace "gem 'mini_racer'", "gem 'mini_racer', '0.6.3'" | Set-Content Gemfile

      - name: Install dependencies
        shell: pwsh
        run: |
          $env:PATH = "C:\Ruby32-x64\bin;$env:PATH"
          bundle install

      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          propertyPath: "giscus.repo"
          value: ${{ github.repository }}

      - name: Install and Build 🔧
        shell: pwsh
        run: |
          $env:PATH = "C:\Ruby32-x64\bin;$env:PATH"
          pip3 install --upgrade jupyter
          $env:JEKYLL_ENV = "production"
          bundle exec jekyll build --trace

      - name: Purge unused CSS 🧹
        shell: pwsh
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site